---
# ArgoCD Installation using official manifests
# This installs ArgoCD v2.9.3 in the argocd namespace

apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    app: argocd
