---
# ArgoCD App of Apps Pattern
# This deploys all microservices applications at once

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-apps
  namespace: argocd
  labels:
    app: app-of-apps
    tier: orchestration
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: microservices
  
  source:
    repoURL: https://github.com/YOUR_ORG/bestproject2.git  # Update with your repo
    targetRevision: main
    path: argocd/applications
    directory:
      recurse: false
      include: '*.yaml'
      exclude: 'app-of-apps.yaml'
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    
    syncOptions:
      - CreateNamespace=true
    
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
