---
# ArgoCD Application for Product Catalog Service (Python/FastAPI)
# This defines how ArgoCD should deploy and manage the product-catalog service

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-catalog
  namespace: argocd
  labels:
    app: product-catalog
    service: microservices
    language: python
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project reference
  project: microservices
  
  # Source repository
  source:
    repoURL: https://github.com/YOUR_ORG/bestproject2.git  # Update with your repo
    targetRevision: main
    path: infrastructure/kubernetes/helm-charts/product-catalog
    
    # Helm values
    helm:
      releaseName: product-catalog
      values: |
        replicaCount: 2
        
        image:
          repository: product-catalog
          tag: latest
          pullPolicy: IfNotPresent
        
        service:
          type: ClusterIP
          port: 8000
          targetPort: 8000
        
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: product-catalog.example.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: product-catalog-tls
              hosts:
                - product-catalog.example.com
        
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        
        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 5
          targetCPUUtilizationPercentage: 70
          targetMemoryUtilizationPercentage: 80
        
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: product-catalog-url
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: url
          - name: ELASTICSEARCH_URL
            value: "http://elasticsearch:9200"
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: secret
        
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /api/v1/ready
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
  
  # Destination cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices
  
  # Sync policy
  syncPolicy:
    automated:
      prune: true      # Remove resources not in git
      selfHeal: true   # Auto-sync when cluster state differs
      allowEmpty: false
    
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Ignore differences in certain fields
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignore replica count changes (HPA manages this)
  
  # Health assessment
  revisionHistoryLimit: 10
